FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install -g typescript
RUN tsc

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY index.html .
COPY styles.css .
COPY --from=builder /app/dist/main.js ./main.js
