FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Adiciona verificação após build
RUN npm run build && ls -la && ls -la dist


ENV PORT=3000
EXPOSE 3000

CMD ["node", "dist/index.js"]
