# Etapa de build com Node e TypeScript
FROM node:20 AS build
WORKDIR /app
COPY package.json package-lock.json* tsconfig.json main.ts ./
RUN npm install
RUN npx tsc

# Etapa final com NGINX
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY index.html .
COPY styles.css .
COPY --from=build /app/dist/main.js ./main.js
